// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ChaCha20XOR_chacha20_block (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_r_address0,
        in_r_ce0,
        in_r_q0,
        in_r_address1,
        in_r_ce1,
        in_r_q1,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0,
        out_r_address1,
        out_r_ce1,
        out_r_we1,
        out_r_d1
);

parameter    ap_ST_fsm_state1 = 30'd1;
parameter    ap_ST_fsm_state2 = 30'd2;
parameter    ap_ST_fsm_state3 = 30'd4;
parameter    ap_ST_fsm_state4 = 30'd8;
parameter    ap_ST_fsm_state5 = 30'd16;
parameter    ap_ST_fsm_state6 = 30'd32;
parameter    ap_ST_fsm_state7 = 30'd64;
parameter    ap_ST_fsm_state8 = 30'd128;
parameter    ap_ST_fsm_state9 = 30'd256;
parameter    ap_ST_fsm_state10 = 30'd512;
parameter    ap_ST_fsm_state11 = 30'd1024;
parameter    ap_ST_fsm_state12 = 30'd2048;
parameter    ap_ST_fsm_state13 = 30'd4096;
parameter    ap_ST_fsm_state14 = 30'd8192;
parameter    ap_ST_fsm_state15 = 30'd16384;
parameter    ap_ST_fsm_state16 = 30'd32768;
parameter    ap_ST_fsm_state17 = 30'd65536;
parameter    ap_ST_fsm_state18 = 30'd131072;
parameter    ap_ST_fsm_state19 = 30'd262144;
parameter    ap_ST_fsm_state20 = 30'd524288;
parameter    ap_ST_fsm_state21 = 30'd1048576;
parameter    ap_ST_fsm_state22 = 30'd2097152;
parameter    ap_ST_fsm_state23 = 30'd4194304;
parameter    ap_ST_fsm_state24 = 30'd8388608;
parameter    ap_ST_fsm_state25 = 30'd16777216;
parameter    ap_ST_fsm_state26 = 30'd33554432;
parameter    ap_ST_fsm_state27 = 30'd67108864;
parameter    ap_ST_fsm_state28 = 30'd134217728;
parameter    ap_ST_fsm_state29 = 30'd268435456;
parameter    ap_ST_fsm_state30 = 30'd536870912;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] in_r_address0;
output   in_r_ce0;
input  [31:0] in_r_q0;
output  [3:0] in_r_address1;
output   in_r_ce1;
input  [31:0] in_r_q1;
output  [5:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [7:0] out_r_d0;
output  [5:0] out_r_address1;
output   out_r_ce1;
output   out_r_we1;
output  [7:0] out_r_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] in_r_address0;
reg in_r_ce0;
reg[3:0] in_r_address1;
reg in_r_ce1;
reg[5:0] out_r_address0;
reg out_r_ce0;
reg out_r_we0;
reg[7:0] out_r_d0;
reg[5:0] out_r_address1;
reg out_r_ce1;
reg out_r_we1;
reg[7:0] out_r_d1;

(* fsm_encoding = "none" *) reg   [29:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] reg_731;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state27;
reg   [7:0] reg_736;
reg   [7:0] reg_741;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state29;
reg   [7:0] reg_746;
reg   [31:0] in_load_reg_2440;
wire    ap_CS_fsm_state2;
reg   [31:0] in_load_1_reg_2445;
reg   [31:0] in_load_2_reg_2460;
wire    ap_CS_fsm_state3;
reg   [31:0] in_load_3_reg_2465;
reg   [31:0] in_load_4_reg_2480;
wire    ap_CS_fsm_state4;
reg   [31:0] in_load_5_reg_2485;
reg   [31:0] in_load_6_reg_2500;
wire    ap_CS_fsm_state5;
reg   [31:0] in_load_7_reg_2505;
reg   [31:0] in_load_8_reg_2520;
wire    ap_CS_fsm_state6;
reg   [31:0] in_load_9_reg_2525;
reg   [31:0] in_load_10_reg_2540;
wire    ap_CS_fsm_state7;
reg   [31:0] in_load_11_reg_2545;
reg   [31:0] in_load_12_reg_2560;
wire    ap_CS_fsm_state8;
reg   [31:0] in_load_13_reg_2565;
wire    ap_CS_fsm_state9;
reg   [31:0] in_load_14_reg_2650;
reg   [31:0] in_load_15_reg_2660;
reg   [31:0] t2_load_1_reg_2673;
wire    ap_CS_fsm_state10;
wire   [0:0] icmp_ln81_fu_839_p2;
reg   [31:0] t2_12_load_1_reg_2678;
wire   [31:0] t1_20_fu_845_p2;
reg   [31:0] t1_20_reg_2683;
wire   [31:0] t1_22_fu_851_p2;
reg   [31:0] t1_22_reg_2689;
wire   [31:0] t4_7_fu_877_p3;
reg   [31:0] t4_7_reg_2694;
wire   [31:0] t3_22_fu_885_p2;
reg   [31:0] t3_22_reg_2699;
wire   [19:0] trunc_ln29_5_fu_897_p1;
reg   [19:0] trunc_ln29_5_reg_2704;
reg   [11:0] lshr_ln29_5_reg_2709;
wire   [31:0] t1_24_fu_911_p2;
reg   [31:0] t1_24_reg_2714;
wire   [31:0] t4_41_fu_937_p3;
reg   [31:0] t4_41_reg_2719;
wire   [31:0] t3_24_fu_945_p2;
reg   [31:0] t3_24_reg_2724;
wire   [31:0] t2_1_fu_971_p3;
reg   [31:0] t2_1_reg_2729;
wire   [31:0] t1_26_fu_979_p2;
reg   [31:0] t1_26_reg_2735;
wire   [31:0] t4_2_fu_1032_p3;
reg   [31:0] t4_2_reg_2748;
wire    ap_CS_fsm_state11;
wire   [31:0] t3_20_fu_1040_p2;
reg   [31:0] t3_20_reg_2753;
wire   [31:0] t2_2_fu_1065_p3;
reg   [31:0] t2_2_reg_2758;
wire   [31:0] t1_21_fu_1073_p2;
reg   [31:0] t1_21_reg_2763;
wire   [31:0] t1_23_fu_1084_p2;
reg   [31:0] t1_23_reg_2769;
wire   [31:0] t4_9_fu_1108_p3;
reg   [31:0] t4_9_reg_2774;
wire   [31:0] t3_23_fu_1116_p2;
reg   [31:0] t3_23_reg_2779;
wire   [31:0] t2_9_fu_1141_p3;
reg   [31:0] t2_9_reg_2784;
wire   [31:0] t1_25_fu_1149_p2;
reg   [31:0] t1_25_reg_2790;
wire   [31:0] t4_43_fu_1172_p3;
reg   [31:0] t4_43_reg_2795;
wire   [31:0] t3_25_fu_1180_p2;
reg   [31:0] t3_25_reg_2800;
wire   [31:0] t4_45_fu_1204_p3;
reg   [31:0] t4_45_reg_2806;
wire   [31:0] t3_26_fu_1212_p2;
reg   [31:0] t3_26_reg_2811;
wire   [31:0] t2_5_fu_1237_p3;
reg   [31:0] t2_5_reg_2816;
wire   [31:0] t1_27_fu_1245_p2;
reg   [31:0] t1_27_reg_2821;
wire   [31:0] t3_21_fu_1276_p2;
reg   [31:0] t3_21_reg_2827;
wire    ap_CS_fsm_state12;
wire   [31:0] t2_46_fu_1300_p3;
reg   [31:0] t2_46_reg_2832;
wire   [31:0] t2_3_fu_1326_p3;
reg   [31:0] t2_3_reg_2837;
wire   [31:0] t2_7_fu_1384_p3;
reg   [31:0] t2_7_reg_2842;
wire   [31:0] t1_28_fu_1392_p2;
reg   [31:0] t1_28_reg_2847;
wire   [31:0] t4_49_fu_1416_p3;
reg   [31:0] t4_49_reg_2852;
wire   [31:0] t3_28_fu_1424_p2;
reg   [31:0] t3_28_reg_2857;
wire   [31:0] t1_30_fu_1429_p2;
reg   [31:0] t1_30_reg_2863;
wire   [31:0] t4_53_fu_1454_p3;
reg   [31:0] t4_53_reg_2868;
wire   [31:0] t3_30_fu_1462_p2;
reg   [31:0] t3_30_reg_2873;
wire   [31:0] t1_32_fu_1468_p2;
reg   [31:0] t1_32_reg_2879;
wire   [31:0] t1_34_fu_1473_p2;
reg   [31:0] t1_34_reg_2885;
wire   [31:0] t2_10_fu_1496_p3;
reg   [31:0] t2_10_reg_2891;
wire    ap_CS_fsm_state13;
wire   [31:0] t3_29_fu_1536_p2;
reg   [31:0] t3_29_reg_2896;
wire   [31:0] t2_11_fu_1559_p3;
reg   [31:0] t2_11_reg_2902;
wire   [31:0] t3_31_fu_1599_p2;
reg   [31:0] t3_31_reg_2907;
wire   [31:0] t4_57_fu_1622_p3;
reg   [31:0] t4_57_reg_2913;
wire   [31:0] t3_32_fu_1630_p2;
reg   [31:0] t3_32_reg_2918;
wire   [31:0] t2_13_fu_1654_p3;
reg   [31:0] t2_13_reg_2923;
wire   [31:0] t1_33_fu_1662_p2;
reg   [31:0] t1_33_reg_2928;
wire   [31:0] t4_61_fu_1685_p3;
reg   [31:0] t4_61_reg_2934;
wire   [31:0] t3_34_fu_1693_p2;
reg   [31:0] t3_34_reg_2939;
wire   [31:0] t2_48_fu_1717_p3;
reg   [31:0] t2_48_reg_2944;
wire   [31:0] t1_35_fu_1725_p2;
reg   [31:0] t1_35_reg_2949;
wire    ap_CS_fsm_state22;
wire   [0:0] tmp_fu_2066_p3;
wire   [3:0] trunc_ln65_fu_2074_p1;
reg   [3:0] trunc_ln65_reg_2963;
wire   [5:0] shl_ln_fu_2089_p3;
reg   [5:0] shl_ln_reg_2971;
wire   [3:0] or_ln63_fu_2137_p2;
reg   [3:0] or_ln63_reg_2977;
wire    ap_CS_fsm_state24;
wire   [5:0] shl_ln65_1_fu_2147_p3;
reg   [5:0] shl_ln65_1_reg_2987;
wire   [3:0] or_ln63_1_fu_2195_p2;
reg   [3:0] or_ln63_1_reg_2993;
wire    ap_CS_fsm_state26;
wire   [5:0] shl_ln65_2_fu_2205_p3;
reg   [5:0] shl_ln65_2_reg_3003;
wire   [3:0] or_ln63_2_fu_2253_p2;
reg   [3:0] or_ln63_2_reg_3009;
wire    ap_CS_fsm_state28;
wire   [5:0] shl_ln65_3_fu_2263_p3;
reg   [5:0] shl_ln65_3_reg_3019;
reg   [3:0] x_address0;
reg    x_ce0;
reg    x_we0;
reg   [31:0] x_d0;
wire   [31:0] x_q0;
reg   [3:0] x_address1;
reg    x_ce1;
reg    x_we1;
reg   [31:0] x_d1;
wire   [31:0] x_q1;
wire   [63:0] zext_ln63_fu_2061_p1;
wire   [63:0] zext_ln65_fu_2096_p1;
wire   [63:0] zext_ln9_fu_2112_p1;
wire   [63:0] zext_ln10_fu_2122_p1;
wire   [63:0] zext_ln11_fu_2132_p1;
wire   [63:0] zext_ln65_1_fu_2142_p1;
wire   [63:0] zext_ln65_2_fu_2154_p1;
wire   [63:0] zext_ln9_1_fu_2170_p1;
wire   [63:0] zext_ln10_1_fu_2180_p1;
wire   [63:0] zext_ln11_1_fu_2190_p1;
wire   [63:0] zext_ln65_3_fu_2200_p1;
wire   [63:0] zext_ln65_4_fu_2212_p1;
wire   [63:0] zext_ln9_2_fu_2228_p1;
wire   [63:0] zext_ln10_2_fu_2238_p1;
wire   [63:0] zext_ln11_2_fu_2248_p1;
wire   [63:0] zext_ln65_5_fu_2258_p1;
wire   [63:0] zext_ln65_6_fu_2270_p1;
wire   [63:0] zext_ln9_3_fu_2286_p1;
wire   [63:0] zext_ln10_3_fu_2296_p1;
wire    ap_CS_fsm_state30;
wire   [63:0] zext_ln11_3_fu_2306_p1;
reg   [4:0] i_fu_106;
wire   [4:0] i_5_fu_985_p2;
reg   [31:0] t1_fu_110;
wire   [31:0] t1_29_fu_1504_p2;
reg   [31:0] t2_fu_114;
wire   [31:0] or_ln_fu_1910_p3;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state16;
reg   [31:0] t3_fu_118;
wire   [31:0] t3_33_fu_1828_p2;
wire    ap_CS_fsm_state18;
reg   [31:0] t4_fu_122;
wire   [31:0] t4_55_fu_1591_p3;
wire    ap_CS_fsm_state20;
reg   [31:0] t1_3_fu_126;
wire   [31:0] t1_31_fu_1567_p2;
reg   [31:0] t2_4_fu_130;
wire   [31:0] or_ln29_s_fu_1768_p3;
reg   [31:0] t3_3_fu_134;
wire   [31:0] t3_35_fu_1886_p2;
reg   [31:0] t4_5_fu_138;
wire   [31:0] t4_59_fu_1820_p3;
reg   [31:0] t1_6_fu_142;
wire    ap_CS_fsm_state15;
reg   [31:0] t2_8_fu_146;
wire   [31:0] or_ln29_1_fu_1794_p3;
wire    ap_CS_fsm_state17;
reg   [31:0] t3_6_fu_150;
wire    ap_CS_fsm_state19;
reg   [31:0] t4_10_fu_154;
wire   [31:0] t4_63_fu_1878_p3;
wire    ap_CS_fsm_state21;
reg   [31:0] t1_9_fu_158;
reg   [31:0] t2_12_fu_162;
wire   [31:0] or_ln29_2_fu_1852_p3;
reg   [31:0] t3_9_fu_166;
reg   [31:0] t4_15_fu_170;
wire   [31:0] t4_51_fu_1528_p3;
reg   [4:0] i_3_fu_178;
wire   [4:0] add_ln63_fu_2078_p2;
wire   [31:0] add_ln95_fu_996_p2;
wire   [31:0] add_ln95_1_fu_1002_p2;
wire   [31:0] add_ln95_2_fu_1974_p2;
wire   [31:0] add_ln95_3_fu_1980_p2;
wire   [31:0] add_ln95_4_fu_1986_p2;
wire   [31:0] add_ln95_5_fu_1992_p2;
wire   [31:0] add_ln95_6_fu_1998_p2;
wire   [31:0] add_ln95_7_fu_2004_p2;
wire   [31:0] add_ln95_8_fu_2010_p2;
wire   [31:0] add_ln95_9_fu_2016_p2;
wire   [31:0] add_ln95_10_fu_2022_p2;
wire   [31:0] add_ln95_11_fu_2028_p2;
wire   [31:0] add_ln95_12_fu_2034_p2;
wire   [31:0] add_ln95_13_fu_2040_p2;
wire   [31:0] add_ln95_14_fu_2046_p2;
wire   [31:0] add_ln95_15_fu_2052_p2;
wire   [7:0] trunc_ln8_fu_2101_p1;
wire   [7:0] trunc_ln8_1_fu_2159_p1;
wire   [7:0] trunc_ln8_2_fu_2217_p1;
wire   [7:0] trunc_ln8_3_fu_2275_p1;
wire   [31:0] t4_38_fu_857_p2;
wire   [15:0] trunc_ln29_4_fu_863_p1;
wire   [15:0] lshr_ln29_4_fu_867_p4;
wire   [31:0] t2_34_fu_891_p2;
wire   [31:0] t4_40_fu_917_p2;
wire   [15:0] trunc_ln29_8_fu_923_p1;
wire   [15:0] lshr_ln29_8_fu_927_p4;
wire   [31:0] t2_36_fu_951_p2;
wire   [19:0] trunc_ln29_9_fu_957_p1;
wire   [11:0] lshr_ln29_9_fu_961_p4;
wire   [31:0] t4_36_fu_1013_p2;
wire   [15:0] trunc_ln29_fu_1018_p1;
wire   [15:0] lshr_ln_fu_1022_p4;
wire   [31:0] t2_32_fu_1046_p2;
wire   [19:0] trunc_ln29_1_fu_1051_p1;
wire   [11:0] lshr_ln29_1_fu_1055_p4;
wire   [31:0] t2_6_fu_1078_p3;
wire   [31:0] t4_39_fu_1089_p2;
wire   [23:0] trunc_ln29_6_fu_1094_p1;
wire   [7:0] lshr_ln29_6_fu_1098_p4;
wire   [31:0] t2_35_fu_1121_p2;
wire   [24:0] trunc_ln29_7_fu_1127_p1;
wire   [6:0] lshr_ln29_7_fu_1131_p4;
wire   [31:0] t4_42_fu_1153_p2;
wire   [23:0] trunc_ln29_10_fu_1158_p1;
wire   [7:0] lshr_ln29_s_fu_1162_p4;
wire   [31:0] t4_44_fu_1185_p2;
wire   [15:0] trunc_ln29_12_fu_1190_p1;
wire   [15:0] lshr_ln29_11_fu_1194_p4;
wire   [31:0] t2_38_fu_1218_p2;
wire   [19:0] trunc_ln29_13_fu_1223_p1;
wire   [11:0] lshr_ln29_12_fu_1227_p4;
wire   [31:0] t4_37_fu_1250_p2;
wire   [23:0] trunc_ln29_2_fu_1254_p1;
wire   [7:0] lshr_ln29_2_fu_1258_p4;
wire   [31:0] t4_4_fu_1268_p3;
wire   [31:0] t2_33_fu_1281_p2;
wire   [24:0] trunc_ln29_3_fu_1286_p1;
wire   [6:0] lshr_ln29_3_fu_1290_p4;
wire   [31:0] t2_37_fu_1308_p2;
wire   [24:0] trunc_ln29_11_fu_1312_p1;
wire   [6:0] lshr_ln29_10_fu_1316_p4;
wire   [31:0] t4_46_fu_1334_p2;
wire   [23:0] trunc_ln29_14_fu_1338_p1;
wire   [7:0] lshr_ln29_13_fu_1342_p4;
wire   [31:0] t4_47_fu_1352_p3;
wire   [31:0] t3_27_fu_1360_p2;
wire   [31:0] t2_39_fu_1365_p2;
wire   [24:0] trunc_ln29_15_fu_1370_p1;
wire   [6:0] lshr_ln29_14_fu_1374_p4;
wire   [31:0] t4_48_fu_1396_p2;
wire   [15:0] trunc_ln29_16_fu_1402_p1;
wire   [15:0] lshr_ln29_15_fu_1406_p4;
wire   [31:0] t4_52_fu_1434_p2;
wire   [15:0] trunc_ln29_20_fu_1440_p1;
wire   [15:0] lshr_ln29_19_fu_1444_p4;
wire   [31:0] t2_40_fu_1478_p2;
wire   [19:0] trunc_ln29_17_fu_1482_p1;
wire   [11:0] lshr_ln29_16_fu_1486_p4;
wire   [31:0] t4_50_fu_1509_p2;
wire   [23:0] trunc_ln29_18_fu_1514_p1;
wire   [7:0] lshr_ln29_17_fu_1518_p4;
wire   [31:0] t2_42_fu_1541_p2;
wire   [19:0] trunc_ln29_21_fu_1545_p1;
wire   [11:0] lshr_ln29_20_fu_1549_p4;
wire   [31:0] t4_54_fu_1572_p2;
wire   [23:0] trunc_ln29_22_fu_1577_p1;
wire   [7:0] lshr_ln29_21_fu_1581_p4;
wire   [31:0] t4_56_fu_1604_p2;
wire   [15:0] trunc_ln29_24_fu_1608_p1;
wire   [15:0] lshr_ln29_23_fu_1612_p4;
wire   [31:0] t2_44_fu_1635_p2;
wire   [19:0] trunc_ln29_25_fu_1640_p1;
wire   [11:0] lshr_ln29_24_fu_1644_p4;
wire   [31:0] t4_60_fu_1667_p2;
wire   [15:0] trunc_ln29_28_fu_1671_p1;
wire   [15:0] lshr_ln29_27_fu_1675_p4;
wire   [31:0] t2_47_fu_1698_p2;
wire   [19:0] trunc_ln29_29_fu_1703_p1;
wire   [11:0] lshr_ln29_28_fu_1707_p4;
wire   [31:0] t2_41_fu_1750_p2;
wire   [24:0] trunc_ln29_19_fu_1754_p1;
wire   [6:0] lshr_ln29_18_fu_1758_p4;
wire   [31:0] t2_43_fu_1776_p2;
wire   [24:0] trunc_ln29_23_fu_1780_p1;
wire   [6:0] lshr_ln29_22_fu_1784_p4;
wire   [31:0] t4_58_fu_1802_p2;
wire   [23:0] trunc_ln29_26_fu_1806_p1;
wire   [7:0] lshr_ln29_25_fu_1810_p4;
wire   [31:0] t2_45_fu_1833_p2;
wire   [24:0] trunc_ln29_27_fu_1838_p1;
wire   [6:0] lshr_ln29_26_fu_1842_p4;
wire   [31:0] t4_62_fu_1860_p2;
wire   [23:0] trunc_ln29_30_fu_1864_p1;
wire   [7:0] lshr_ln29_29_fu_1868_p4;
wire   [31:0] t2_49_fu_1891_p2;
wire   [24:0] trunc_ln29_31_fu_1896_p1;
wire   [6:0] lshr_ln29_30_fu_1900_p4;
wire   [5:0] or_ln9_fu_2106_p2;
wire   [5:0] or_ln10_fu_2117_p2;
wire   [5:0] or_ln11_fu_2127_p2;
wire   [5:0] or_ln9_1_fu_2164_p2;
wire   [5:0] or_ln10_1_fu_2175_p2;
wire   [5:0] or_ln11_1_fu_2185_p2;
wire   [5:0] or_ln9_2_fu_2222_p2;
wire   [5:0] or_ln10_2_fu_2233_p2;
wire   [5:0] or_ln11_2_fu_2243_p2;
wire   [5:0] or_ln9_3_fu_2280_p2;
wire   [5:0] or_ln10_3_fu_2291_p2;
wire   [5:0] or_ln11_3_fu_2301_p2;
reg   [29:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 30'd1;
end

ChaCha20XOR_chacha20_block_x_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
x_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(x_address0),
    .ce0(x_ce0),
    .we0(x_we0),
    .d0(x_d0),
    .q0(x_q0),
    .address1(x_address1),
    .ce1(x_ce1),
    .we1(x_we1),
    .d1(x_d1),
    .q1(x_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln81_fu_839_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        i_3_fu_178 <= 5'd0;
    end else if (((tmp_fu_2066_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state22))) begin
        i_3_fu_178 <= add_ln63_fu_2078_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_106 <= 5'd20;
    end else if (((icmp_ln81_fu_839_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        i_fu_106 <= i_5_fu_985_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        t1_3_fu_126 <= in_r_q0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        t1_3_fu_126 <= t1_31_fu_1567_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        t1_6_fu_142 <= in_r_q1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        t1_6_fu_142 <= t1_33_reg_2928;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        t1_9_fu_158 <= in_r_q0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        t1_9_fu_158 <= t1_35_reg_2949;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        t1_fu_110 <= in_r_q1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        t1_fu_110 <= t1_29_fu_1504_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        t2_12_fu_162 <= in_r_q0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        t2_12_fu_162 <= or_ln29_2_fu_1852_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        t2_4_fu_130 <= in_r_q0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        t2_4_fu_130 <= or_ln29_s_fu_1768_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        t2_8_fu_146 <= in_r_q1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        t2_8_fu_146 <= or_ln29_1_fu_1794_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        t2_fu_114 <= in_r_q1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        t2_fu_114 <= or_ln_fu_1910_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        t3_3_fu_134 <= in_r_q0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        t3_3_fu_134 <= t3_35_fu_1886_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t3_6_fu_150 <= in_r_q1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        t3_6_fu_150 <= t3_29_reg_2896;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t3_9_fu_166 <= in_r_q0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        t3_9_fu_166 <= t3_31_reg_2907;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        t3_fu_118 <= in_r_q1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        t3_fu_118 <= t3_33_fu_1828_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        t4_10_fu_154 <= in_r_q1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        t4_10_fu_154 <= t4_63_fu_1878_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        t4_15_fu_170 <= in_r_q0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        t4_15_fu_170 <= t4_51_fu_1528_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        t4_5_fu_138 <= in_r_q0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        t4_5_fu_138 <= t4_59_fu_1820_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        t4_fu_122 <= in_r_q1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        t4_fu_122 <= t4_55_fu_1591_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        in_load_10_reg_2540 <= in_r_q1;
        in_load_11_reg_2545 <= in_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        in_load_12_reg_2560 <= in_r_q1;
        in_load_13_reg_2565 <= in_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        in_load_14_reg_2650 <= in_r_q1;
        in_load_15_reg_2660 <= in_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        in_load_1_reg_2445 <= in_r_q0;
        in_load_reg_2440 <= in_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_load_2_reg_2460 <= in_r_q1;
        in_load_3_reg_2465 <= in_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        in_load_4_reg_2480 <= in_r_q1;
        in_load_5_reg_2485 <= in_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_load_6_reg_2500 <= in_r_q1;
        in_load_7_reg_2505 <= in_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        in_load_8_reg_2520 <= in_r_q1;
        in_load_9_reg_2525 <= in_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln81_fu_839_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        lshr_ln29_5_reg_2709 <= {{t2_34_fu_891_p2[31:20]}};
        t1_20_reg_2683 <= t1_20_fu_845_p2;
        t1_22_reg_2689 <= t1_22_fu_851_p2;
        t1_24_reg_2714 <= t1_24_fu_911_p2;
        t1_26_reg_2735 <= t1_26_fu_979_p2;
        t2_12_load_1_reg_2678 <= t2_12_fu_162;
        t2_1_reg_2729 <= t2_1_fu_971_p3;
        t2_load_1_reg_2673 <= t2_fu_114;
        t3_22_reg_2699 <= t3_22_fu_885_p2;
        t3_24_reg_2724 <= t3_24_fu_945_p2;
        t4_41_reg_2719 <= t4_41_fu_937_p3;
        t4_7_reg_2694 <= t4_7_fu_877_p3;
        trunc_ln29_5_reg_2704 <= trunc_ln29_5_fu_897_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        or_ln63_1_reg_2993[0] <= or_ln63_1_fu_2195_p2[0];
or_ln63_1_reg_2993[3 : 2] <= or_ln63_1_fu_2195_p2[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        or_ln63_2_reg_3009[3 : 2] <= or_ln63_2_fu_2253_p2[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        or_ln63_reg_2977[3 : 1] <= or_ln63_fu_2137_p2[3 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state23))) begin
        reg_731 <= {{x_q0[23:16]}};
        reg_736 <= {{x_q0[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state25))) begin
        reg_741 <= {{x_q1[23:16]}};
        reg_746 <= {{x_q1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        shl_ln65_1_reg_2987[5 : 3] <= shl_ln65_1_fu_2147_p3[5 : 3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        shl_ln65_2_reg_3003[2] <= shl_ln65_2_fu_2205_p3[2];
shl_ln65_2_reg_3003[5 : 4] <= shl_ln65_2_fu_2205_p3[5 : 4];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        shl_ln65_3_reg_3019[5 : 4] <= shl_ln65_3_fu_2263_p3[5 : 4];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        shl_ln_reg_2971[5 : 2] <= shl_ln_fu_2089_p3[5 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        t1_21_reg_2763 <= t1_21_fu_1073_p2;
        t1_23_reg_2769 <= t1_23_fu_1084_p2;
        t1_25_reg_2790 <= t1_25_fu_1149_p2;
        t1_27_reg_2821 <= t1_27_fu_1245_p2;
        t2_2_reg_2758 <= t2_2_fu_1065_p3;
        t2_5_reg_2816 <= t2_5_fu_1237_p3;
        t2_9_reg_2784 <= t2_9_fu_1141_p3;
        t3_20_reg_2753 <= t3_20_fu_1040_p2;
        t3_23_reg_2779 <= t3_23_fu_1116_p2;
        t3_25_reg_2800 <= t3_25_fu_1180_p2;
        t3_26_reg_2811 <= t3_26_fu_1212_p2;
        t4_2_reg_2748 <= t4_2_fu_1032_p3;
        t4_43_reg_2795 <= t4_43_fu_1172_p3;
        t4_45_reg_2806 <= t4_45_fu_1204_p3;
        t4_9_reg_2774 <= t4_9_fu_1108_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        t1_28_reg_2847 <= t1_28_fu_1392_p2;
        t1_30_reg_2863 <= t1_30_fu_1429_p2;
        t1_32_reg_2879 <= t1_32_fu_1468_p2;
        t1_34_reg_2885 <= t1_34_fu_1473_p2;
        t2_3_reg_2837 <= t2_3_fu_1326_p3;
        t2_46_reg_2832 <= t2_46_fu_1300_p3;
        t2_7_reg_2842 <= t2_7_fu_1384_p3;
        t3_21_reg_2827 <= t3_21_fu_1276_p2;
        t3_28_reg_2857 <= t3_28_fu_1424_p2;
        t3_30_reg_2873 <= t3_30_fu_1462_p2;
        t4_49_reg_2852 <= t4_49_fu_1416_p3;
        t4_53_reg_2868 <= t4_53_fu_1454_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        t1_33_reg_2928 <= t1_33_fu_1662_p2;
        t1_35_reg_2949 <= t1_35_fu_1725_p2;
        t2_10_reg_2891 <= t2_10_fu_1496_p3;
        t2_11_reg_2902 <= t2_11_fu_1559_p3;
        t2_13_reg_2923 <= t2_13_fu_1654_p3;
        t2_48_reg_2944 <= t2_48_fu_1717_p3;
        t3_29_reg_2896 <= t3_29_fu_1536_p2;
        t3_31_reg_2907 <= t3_31_fu_1599_p2;
        t3_32_reg_2918 <= t3_32_fu_1630_p2;
        t3_34_reg_2939 <= t3_34_fu_1693_p2;
        t4_57_reg_2913 <= t4_57_fu_1622_p3;
        t4_61_reg_2934 <= t4_61_fu_1685_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_2066_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state22))) begin
        trunc_ln65_reg_2963 <= trunc_ln65_fu_2074_p1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_fu_2066_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state22)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_2066_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        in_r_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        in_r_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_r_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        in_r_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        in_r_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_r_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_r_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        in_r_address0 = 64'd1;
    end else begin
        in_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        in_r_address1 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        in_r_address1 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_r_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        in_r_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        in_r_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_r_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_r_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        in_r_address1 = 64'd0;
    end else begin
        in_r_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_r_ce0 = 1'b1;
    end else begin
        in_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_r_ce1 = 1'b1;
    end else begin
        in_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        out_r_address0 = zext_ln11_3_fu_2306_p1;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        out_r_address0 = zext_ln9_3_fu_2286_p1;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        out_r_address0 = zext_ln11_2_fu_2248_p1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        out_r_address0 = zext_ln9_2_fu_2228_p1;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        out_r_address0 = zext_ln11_1_fu_2190_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        out_r_address0 = zext_ln9_1_fu_2170_p1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        out_r_address0 = zext_ln11_fu_2132_p1;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        out_r_address0 = zext_ln9_fu_2112_p1;
    end else begin
        out_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        out_r_address1 = zext_ln10_3_fu_2296_p1;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        out_r_address1 = zext_ln65_6_fu_2270_p1;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        out_r_address1 = zext_ln10_2_fu_2238_p1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        out_r_address1 = zext_ln65_4_fu_2212_p1;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        out_r_address1 = zext_ln10_1_fu_2180_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        out_r_address1 = zext_ln65_2_fu_2154_p1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        out_r_address1 = zext_ln10_fu_2122_p1;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        out_r_address1 = zext_ln65_fu_2096_p1;
    end else begin
        out_r_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state24))) begin
        out_r_ce0 = 1'b1;
    end else begin
        out_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state24))) begin
        out_r_ce1 = 1'b1;
    end else begin
        out_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state26))) begin
        out_r_d0 = reg_746;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state25))) begin
        out_r_d0 = {{x_q1[15:8]}};
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state24))) begin
        out_r_d0 = reg_736;
    end else if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state23))) begin
        out_r_d0 = {{x_q0[15:8]}};
    end else begin
        out_r_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        out_r_d1 = trunc_ln8_3_fu_2275_p1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        out_r_d1 = trunc_ln8_2_fu_2217_p1;
    end else if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state26))) begin
        out_r_d1 = reg_741;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        out_r_d1 = trunc_ln8_1_fu_2159_p1;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state24))) begin
        out_r_d1 = reg_731;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        out_r_d1 = trunc_ln8_fu_2101_p1;
    end else begin
        out_r_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state24))) begin
        out_r_we0 = 1'b1;
    end else begin
        out_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state24))) begin
        out_r_we1 = 1'b1;
    end else begin
        out_r_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        x_address0 = zext_ln65_3_fu_2200_p1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        x_address0 = zext_ln63_fu_2061_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        x_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        x_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        x_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        x_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        x_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        x_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        x_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        x_address0 = 64'd1;
    end else begin
        x_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        x_address1 = zext_ln65_5_fu_2258_p1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        x_address1 = zext_ln65_1_fu_2142_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        x_address1 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        x_address1 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        x_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        x_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        x_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        x_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        x_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        x_address1 = 64'd0;
    end else begin
        x_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state10))) begin
        x_ce0 = 1'b1;
    end else begin
        x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state10))) begin
        x_ce1 = 1'b1;
    end else begin
        x_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        x_d0 = add_ln95_15_fu_2052_p2;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        x_d0 = add_ln95_13_fu_2040_p2;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        x_d0 = add_ln95_11_fu_2028_p2;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        x_d0 = add_ln95_9_fu_2016_p2;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        x_d0 = add_ln95_7_fu_2004_p2;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        x_d0 = add_ln95_5_fu_1992_p2;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        x_d0 = add_ln95_3_fu_1980_p2;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        x_d0 = add_ln95_1_fu_1002_p2;
    end else begin
        x_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        x_d1 = add_ln95_14_fu_2046_p2;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        x_d1 = add_ln95_12_fu_2034_p2;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        x_d1 = add_ln95_10_fu_2022_p2;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        x_d1 = add_ln95_8_fu_2010_p2;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        x_d1 = add_ln95_6_fu_1998_p2;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        x_d1 = add_ln95_4_fu_1986_p2;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        x_d1 = add_ln95_2_fu_1974_p2;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        x_d1 = add_ln95_fu_996_p2;
    end else begin
        x_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | ((icmp_ln81_fu_839_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10)))) begin
        x_we0 = 1'b1;
    end else begin
        x_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | ((icmp_ln81_fu_839_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10)))) begin
        x_we1 = 1'b1;
    end else begin
        x_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((icmp_ln81_fu_839_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if (((tmp_fu_2066_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln63_fu_2078_p2 = (i_3_fu_178 + 5'd4);

assign add_ln95_10_fu_2022_p2 = (in_load_10_reg_2540 + t3_6_fu_150);

assign add_ln95_11_fu_2028_p2 = (in_load_11_reg_2545 + t3_9_fu_166);

assign add_ln95_12_fu_2034_p2 = (in_load_12_reg_2560 + t4_fu_122);

assign add_ln95_13_fu_2040_p2 = (in_load_13_reg_2565 + t4_5_fu_138);

assign add_ln95_14_fu_2046_p2 = (in_load_14_reg_2650 + t4_10_fu_154);

assign add_ln95_15_fu_2052_p2 = (in_load_15_reg_2660 + t4_15_fu_170);

assign add_ln95_1_fu_1002_p2 = (in_load_1_reg_2445 + t1_3_fu_126);

assign add_ln95_2_fu_1974_p2 = (in_load_2_reg_2460 + t1_6_fu_142);

assign add_ln95_3_fu_1980_p2 = (in_load_3_reg_2465 + t1_9_fu_158);

assign add_ln95_4_fu_1986_p2 = (in_load_4_reg_2480 + t2_fu_114);

assign add_ln95_5_fu_1992_p2 = (in_load_5_reg_2485 + t2_4_fu_130);

assign add_ln95_6_fu_1998_p2 = (in_load_6_reg_2500 + t2_8_fu_146);

assign add_ln95_7_fu_2004_p2 = (in_load_7_reg_2505 + t2_12_fu_162);

assign add_ln95_8_fu_2010_p2 = (in_load_8_reg_2520 + t3_fu_118);

assign add_ln95_9_fu_2016_p2 = (in_load_9_reg_2525 + t3_3_fu_134);

assign add_ln95_fu_996_p2 = (in_load_reg_2440 + t1_fu_110);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign i_5_fu_985_p2 = ($signed(i_fu_106) + $signed(5'd30));

assign icmp_ln81_fu_839_p2 = ((i_fu_106 == 5'd0) ? 1'b1 : 1'b0);

assign lshr_ln29_10_fu_1316_p4 = {{t2_37_fu_1308_p2[31:25]}};

assign lshr_ln29_11_fu_1194_p4 = {{t4_44_fu_1185_p2[31:16]}};

assign lshr_ln29_12_fu_1227_p4 = {{t2_38_fu_1218_p2[31:20]}};

assign lshr_ln29_13_fu_1342_p4 = {{t4_46_fu_1334_p2[31:24]}};

assign lshr_ln29_14_fu_1374_p4 = {{t2_39_fu_1365_p2[31:25]}};

assign lshr_ln29_15_fu_1406_p4 = {{t4_48_fu_1396_p2[31:16]}};

assign lshr_ln29_16_fu_1486_p4 = {{t2_40_fu_1478_p2[31:20]}};

assign lshr_ln29_17_fu_1518_p4 = {{t4_50_fu_1509_p2[31:24]}};

assign lshr_ln29_18_fu_1758_p4 = {{t2_41_fu_1750_p2[31:25]}};

assign lshr_ln29_19_fu_1444_p4 = {{t4_52_fu_1434_p2[31:16]}};

assign lshr_ln29_1_fu_1055_p4 = {{t2_32_fu_1046_p2[31:20]}};

assign lshr_ln29_20_fu_1549_p4 = {{t2_42_fu_1541_p2[31:20]}};

assign lshr_ln29_21_fu_1581_p4 = {{t4_54_fu_1572_p2[31:24]}};

assign lshr_ln29_22_fu_1784_p4 = {{t2_43_fu_1776_p2[31:25]}};

assign lshr_ln29_23_fu_1612_p4 = {{t4_56_fu_1604_p2[31:16]}};

assign lshr_ln29_24_fu_1644_p4 = {{t2_44_fu_1635_p2[31:20]}};

assign lshr_ln29_25_fu_1810_p4 = {{t4_58_fu_1802_p2[31:24]}};

assign lshr_ln29_26_fu_1842_p4 = {{t2_45_fu_1833_p2[31:25]}};

assign lshr_ln29_27_fu_1675_p4 = {{t4_60_fu_1667_p2[31:16]}};

assign lshr_ln29_28_fu_1707_p4 = {{t2_47_fu_1698_p2[31:20]}};

assign lshr_ln29_29_fu_1868_p4 = {{t4_62_fu_1860_p2[31:24]}};

assign lshr_ln29_2_fu_1258_p4 = {{t4_37_fu_1250_p2[31:24]}};

assign lshr_ln29_30_fu_1900_p4 = {{t2_49_fu_1891_p2[31:25]}};

assign lshr_ln29_3_fu_1290_p4 = {{t2_33_fu_1281_p2[31:25]}};

assign lshr_ln29_4_fu_867_p4 = {{t4_38_fu_857_p2[31:16]}};

assign lshr_ln29_6_fu_1098_p4 = {{t4_39_fu_1089_p2[31:24]}};

assign lshr_ln29_7_fu_1131_p4 = {{t2_35_fu_1121_p2[31:25]}};

assign lshr_ln29_8_fu_927_p4 = {{t4_40_fu_917_p2[31:16]}};

assign lshr_ln29_9_fu_961_p4 = {{t2_36_fu_951_p2[31:20]}};

assign lshr_ln29_s_fu_1162_p4 = {{t4_42_fu_1153_p2[31:24]}};

assign lshr_ln_fu_1022_p4 = {{t4_36_fu_1013_p2[31:16]}};

assign or_ln10_1_fu_2175_p2 = (shl_ln65_1_reg_2987 | 6'd2);

assign or_ln10_2_fu_2233_p2 = (shl_ln65_2_reg_3003 | 6'd2);

assign or_ln10_3_fu_2291_p2 = (shl_ln65_3_reg_3019 | 6'd2);

assign or_ln10_fu_2117_p2 = (shl_ln_reg_2971 | 6'd2);

assign or_ln11_1_fu_2185_p2 = (shl_ln65_1_reg_2987 | 6'd3);

assign or_ln11_2_fu_2243_p2 = (shl_ln65_2_reg_3003 | 6'd3);

assign or_ln11_3_fu_2301_p2 = (shl_ln65_3_reg_3019 | 6'd3);

assign or_ln11_fu_2127_p2 = (shl_ln_reg_2971 | 6'd3);

assign or_ln29_1_fu_1794_p3 = {{trunc_ln29_23_fu_1780_p1}, {lshr_ln29_22_fu_1784_p4}};

assign or_ln29_2_fu_1852_p3 = {{trunc_ln29_27_fu_1838_p1}, {lshr_ln29_26_fu_1842_p4}};

assign or_ln29_s_fu_1768_p3 = {{trunc_ln29_19_fu_1754_p1}, {lshr_ln29_18_fu_1758_p4}};

assign or_ln63_1_fu_2195_p2 = (trunc_ln65_reg_2963 | 4'd2);

assign or_ln63_2_fu_2253_p2 = (trunc_ln65_reg_2963 | 4'd3);

assign or_ln63_fu_2137_p2 = (trunc_ln65_reg_2963 | 4'd1);

assign or_ln9_1_fu_2164_p2 = (shl_ln65_1_fu_2147_p3 | 6'd1);

assign or_ln9_2_fu_2222_p2 = (shl_ln65_2_fu_2205_p3 | 6'd1);

assign or_ln9_3_fu_2280_p2 = (shl_ln65_3_fu_2263_p3 | 6'd1);

assign or_ln9_fu_2106_p2 = (shl_ln_fu_2089_p3 | 6'd1);

assign or_ln_fu_1910_p3 = {{trunc_ln29_31_fu_1896_p1}, {lshr_ln29_30_fu_1900_p4}};

assign shl_ln65_1_fu_2147_p3 = {{or_ln63_reg_2977}, {2'd0}};

assign shl_ln65_2_fu_2205_p3 = {{or_ln63_1_reg_2993}, {2'd0}};

assign shl_ln65_3_fu_2263_p3 = {{or_ln63_2_reg_3009}, {2'd0}};

assign shl_ln_fu_2089_p3 = {{trunc_ln65_reg_2963}, {2'd0}};

assign t1_20_fu_845_p2 = (t1_fu_110 + t2_fu_114);

assign t1_21_fu_1073_p2 = (t2_2_fu_1065_p3 + t1_20_reg_2683);

assign t1_22_fu_851_p2 = (t1_3_fu_126 + t2_4_fu_130);

assign t1_23_fu_1084_p2 = (t2_6_fu_1078_p3 + t1_22_reg_2689);

assign t1_24_fu_911_p2 = (t1_6_fu_142 + t2_8_fu_146);

assign t1_25_fu_1149_p2 = (t2_1_reg_2729 + t1_24_reg_2714);

assign t1_26_fu_979_p2 = (t1_9_fu_158 + t2_12_fu_162);

assign t1_27_fu_1245_p2 = (t2_5_fu_1237_p3 + t1_26_reg_2735);

assign t1_28_fu_1392_p2 = (t2_9_reg_2784 + t1_21_reg_2763);

assign t1_29_fu_1504_p2 = (t2_10_fu_1496_p3 + t1_28_reg_2847);

assign t1_30_fu_1429_p2 = (t2_3_fu_1326_p3 + t1_23_reg_2769);

assign t1_31_fu_1567_p2 = (t2_11_fu_1559_p3 + t1_30_reg_2863);

assign t1_32_fu_1468_p2 = (t2_7_fu_1384_p3 + t1_25_reg_2790);

assign t1_33_fu_1662_p2 = (t2_13_fu_1654_p3 + t1_32_reg_2879);

assign t1_34_fu_1473_p2 = (t2_46_fu_1300_p3 + t1_27_reg_2821);

assign t1_35_fu_1725_p2 = (t2_48_fu_1717_p3 + t1_34_reg_2885);

assign t2_10_fu_1496_p3 = {{trunc_ln29_17_fu_1482_p1}, {lshr_ln29_16_fu_1486_p4}};

assign t2_11_fu_1559_p3 = {{trunc_ln29_21_fu_1545_p1}, {lshr_ln29_20_fu_1549_p4}};

assign t2_13_fu_1654_p3 = {{trunc_ln29_25_fu_1640_p1}, {lshr_ln29_24_fu_1644_p4}};

assign t2_1_fu_971_p3 = {{trunc_ln29_9_fu_957_p1}, {lshr_ln29_9_fu_961_p4}};

assign t2_2_fu_1065_p3 = {{trunc_ln29_1_fu_1051_p1}, {lshr_ln29_1_fu_1055_p4}};

assign t2_32_fu_1046_p2 = (t3_20_fu_1040_p2 ^ t2_load_1_reg_2673);

assign t2_33_fu_1281_p2 = (t3_21_fu_1276_p2 ^ t2_2_reg_2758);

assign t2_34_fu_891_p2 = (t3_22_fu_885_p2 ^ t2_4_fu_130);

assign t2_35_fu_1121_p2 = (t3_23_fu_1116_p2 ^ t2_6_fu_1078_p3);

assign t2_36_fu_951_p2 = (t3_24_fu_945_p2 ^ t2_8_fu_146);

assign t2_37_fu_1308_p2 = (t3_25_reg_2800 ^ t2_1_reg_2729);

assign t2_38_fu_1218_p2 = (t3_26_fu_1212_p2 ^ t2_12_load_1_reg_2678);

assign t2_39_fu_1365_p2 = (t3_27_fu_1360_p2 ^ t2_5_reg_2816);

assign t2_3_fu_1326_p3 = {{trunc_ln29_11_fu_1312_p1}, {lshr_ln29_10_fu_1316_p4}};

assign t2_40_fu_1478_p2 = (t3_28_reg_2857 ^ t2_9_reg_2784);

assign t2_41_fu_1750_p2 = (t3_29_reg_2896 ^ t2_10_reg_2891);

assign t2_42_fu_1541_p2 = (t3_30_reg_2873 ^ t2_3_reg_2837);

assign t2_43_fu_1776_p2 = (t3_31_reg_2907 ^ t2_11_reg_2902);

assign t2_44_fu_1635_p2 = (t3_32_fu_1630_p2 ^ t2_7_reg_2842);

assign t2_45_fu_1833_p2 = (t3_33_fu_1828_p2 ^ t2_13_reg_2923);

assign t2_46_fu_1300_p3 = {{trunc_ln29_3_fu_1286_p1}, {lshr_ln29_3_fu_1290_p4}};

assign t2_47_fu_1698_p2 = (t3_34_fu_1693_p2 ^ t2_46_reg_2832);

assign t2_48_fu_1717_p3 = {{trunc_ln29_29_fu_1703_p1}, {lshr_ln29_28_fu_1707_p4}};

assign t2_49_fu_1891_p2 = (t3_35_fu_1886_p2 ^ t2_48_reg_2944);

assign t2_5_fu_1237_p3 = {{trunc_ln29_13_fu_1223_p1}, {lshr_ln29_12_fu_1227_p4}};

assign t2_6_fu_1078_p3 = {{trunc_ln29_5_reg_2704}, {lshr_ln29_5_reg_2709}};

assign t2_7_fu_1384_p3 = {{trunc_ln29_15_fu_1370_p1}, {lshr_ln29_14_fu_1374_p4}};

assign t2_9_fu_1141_p3 = {{trunc_ln29_7_fu_1127_p1}, {lshr_ln29_7_fu_1131_p4}};

assign t3_20_fu_1040_p2 = (t4_2_fu_1032_p3 + t3_fu_118);

assign t3_21_fu_1276_p2 = (t4_4_fu_1268_p3 + t3_20_reg_2753);

assign t3_22_fu_885_p2 = (t4_7_fu_877_p3 + t3_3_fu_134);

assign t3_23_fu_1116_p2 = (t4_9_fu_1108_p3 + t3_22_reg_2699);

assign t3_24_fu_945_p2 = (t4_41_fu_937_p3 + t3_6_fu_150);

assign t3_25_fu_1180_p2 = (t4_43_fu_1172_p3 + t3_24_reg_2724);

assign t3_26_fu_1212_p2 = (t4_45_fu_1204_p3 + t3_9_fu_166);

assign t3_27_fu_1360_p2 = (t4_47_fu_1352_p3 + t3_26_reg_2811);

assign t3_28_fu_1424_p2 = (t4_49_fu_1416_p3 + t3_25_reg_2800);

assign t3_29_fu_1536_p2 = (t4_51_fu_1528_p3 + t3_28_reg_2857);

assign t3_30_fu_1462_p2 = (t4_53_fu_1454_p3 + t3_27_fu_1360_p2);

assign t3_31_fu_1599_p2 = (t4_55_fu_1591_p3 + t3_30_reg_2873);

assign t3_32_fu_1630_p2 = (t3_21_reg_2827 + t4_57_fu_1622_p3);

assign t3_33_fu_1828_p2 = (t4_59_fu_1820_p3 + t3_32_reg_2918);

assign t3_34_fu_1693_p2 = (t4_61_fu_1685_p3 + t3_23_reg_2779);

assign t3_35_fu_1886_p2 = (t4_63_fu_1878_p3 + t3_34_reg_2939);

assign t4_2_fu_1032_p3 = {{trunc_ln29_fu_1018_p1}, {lshr_ln_fu_1022_p4}};

assign t4_36_fu_1013_p2 = (t4_fu_122 ^ t1_20_reg_2683);

assign t4_37_fu_1250_p2 = (t4_2_reg_2748 ^ t1_21_reg_2763);

assign t4_38_fu_857_p2 = (t4_5_fu_138 ^ t1_22_fu_851_p2);

assign t4_39_fu_1089_p2 = (t4_7_reg_2694 ^ t1_23_fu_1084_p2);

assign t4_40_fu_917_p2 = (t4_10_fu_154 ^ t1_24_fu_911_p2);

assign t4_41_fu_937_p3 = {{trunc_ln29_8_fu_923_p1}, {lshr_ln29_8_fu_927_p4}};

assign t4_42_fu_1153_p2 = (t4_41_reg_2719 ^ t1_25_fu_1149_p2);

assign t4_43_fu_1172_p3 = {{trunc_ln29_10_fu_1158_p1}, {lshr_ln29_s_fu_1162_p4}};

assign t4_44_fu_1185_p2 = (t4_15_fu_170 ^ t1_26_reg_2735);

assign t4_45_fu_1204_p3 = {{trunc_ln29_12_fu_1190_p1}, {lshr_ln29_11_fu_1194_p4}};

assign t4_46_fu_1334_p2 = (t4_45_reg_2806 ^ t1_27_reg_2821);

assign t4_47_fu_1352_p3 = {{trunc_ln29_14_fu_1338_p1}, {lshr_ln29_13_fu_1342_p4}};

assign t4_48_fu_1396_p2 = (t4_47_fu_1352_p3 ^ t1_28_fu_1392_p2);

assign t4_49_fu_1416_p3 = {{trunc_ln29_16_fu_1402_p1}, {lshr_ln29_15_fu_1406_p4}};

assign t4_4_fu_1268_p3 = {{trunc_ln29_2_fu_1254_p1}, {lshr_ln29_2_fu_1258_p4}};

assign t4_50_fu_1509_p2 = (t4_49_reg_2852 ^ t1_29_fu_1504_p2);

assign t4_51_fu_1528_p3 = {{trunc_ln29_18_fu_1514_p1}, {lshr_ln29_17_fu_1518_p4}};

assign t4_52_fu_1434_p2 = (t4_4_fu_1268_p3 ^ t1_30_fu_1429_p2);

assign t4_53_fu_1454_p3 = {{trunc_ln29_20_fu_1440_p1}, {lshr_ln29_19_fu_1444_p4}};

assign t4_54_fu_1572_p2 = (t4_53_reg_2868 ^ t1_31_fu_1567_p2);

assign t4_55_fu_1591_p3 = {{trunc_ln29_22_fu_1577_p1}, {lshr_ln29_21_fu_1581_p4}};

assign t4_56_fu_1604_p2 = (t4_9_reg_2774 ^ t1_32_reg_2879);

assign t4_57_fu_1622_p3 = {{trunc_ln29_24_fu_1608_p1}, {lshr_ln29_23_fu_1612_p4}};

assign t4_58_fu_1802_p2 = (t4_57_reg_2913 ^ t1_33_reg_2928);

assign t4_59_fu_1820_p3 = {{trunc_ln29_26_fu_1806_p1}, {lshr_ln29_25_fu_1810_p4}};

assign t4_60_fu_1667_p2 = (t4_43_reg_2795 ^ t1_34_reg_2885);

assign t4_61_fu_1685_p3 = {{trunc_ln29_28_fu_1671_p1}, {lshr_ln29_27_fu_1675_p4}};

assign t4_62_fu_1860_p2 = (t4_61_reg_2934 ^ t1_35_reg_2949);

assign t4_63_fu_1878_p3 = {{trunc_ln29_30_fu_1864_p1}, {lshr_ln29_29_fu_1868_p4}};

assign t4_7_fu_877_p3 = {{trunc_ln29_4_fu_863_p1}, {lshr_ln29_4_fu_867_p4}};

assign t4_9_fu_1108_p3 = {{trunc_ln29_6_fu_1094_p1}, {lshr_ln29_6_fu_1098_p4}};

assign tmp_fu_2066_p3 = i_3_fu_178[32'd4];

assign trunc_ln29_10_fu_1158_p1 = t4_42_fu_1153_p2[23:0];

assign trunc_ln29_11_fu_1312_p1 = t2_37_fu_1308_p2[24:0];

assign trunc_ln29_12_fu_1190_p1 = t4_44_fu_1185_p2[15:0];

assign trunc_ln29_13_fu_1223_p1 = t2_38_fu_1218_p2[19:0];

assign trunc_ln29_14_fu_1338_p1 = t4_46_fu_1334_p2[23:0];

assign trunc_ln29_15_fu_1370_p1 = t2_39_fu_1365_p2[24:0];

assign trunc_ln29_16_fu_1402_p1 = t4_48_fu_1396_p2[15:0];

assign trunc_ln29_17_fu_1482_p1 = t2_40_fu_1478_p2[19:0];

assign trunc_ln29_18_fu_1514_p1 = t4_50_fu_1509_p2[23:0];

assign trunc_ln29_19_fu_1754_p1 = t2_41_fu_1750_p2[24:0];

assign trunc_ln29_1_fu_1051_p1 = t2_32_fu_1046_p2[19:0];

assign trunc_ln29_20_fu_1440_p1 = t4_52_fu_1434_p2[15:0];

assign trunc_ln29_21_fu_1545_p1 = t2_42_fu_1541_p2[19:0];

assign trunc_ln29_22_fu_1577_p1 = t4_54_fu_1572_p2[23:0];

assign trunc_ln29_23_fu_1780_p1 = t2_43_fu_1776_p2[24:0];

assign trunc_ln29_24_fu_1608_p1 = t4_56_fu_1604_p2[15:0];

assign trunc_ln29_25_fu_1640_p1 = t2_44_fu_1635_p2[19:0];

assign trunc_ln29_26_fu_1806_p1 = t4_58_fu_1802_p2[23:0];

assign trunc_ln29_27_fu_1838_p1 = t2_45_fu_1833_p2[24:0];

assign trunc_ln29_28_fu_1671_p1 = t4_60_fu_1667_p2[15:0];

assign trunc_ln29_29_fu_1703_p1 = t2_47_fu_1698_p2[19:0];

assign trunc_ln29_2_fu_1254_p1 = t4_37_fu_1250_p2[23:0];

assign trunc_ln29_30_fu_1864_p1 = t4_62_fu_1860_p2[23:0];

assign trunc_ln29_31_fu_1896_p1 = t2_49_fu_1891_p2[24:0];

assign trunc_ln29_3_fu_1286_p1 = t2_33_fu_1281_p2[24:0];

assign trunc_ln29_4_fu_863_p1 = t4_38_fu_857_p2[15:0];

assign trunc_ln29_5_fu_897_p1 = t2_34_fu_891_p2[19:0];

assign trunc_ln29_6_fu_1094_p1 = t4_39_fu_1089_p2[23:0];

assign trunc_ln29_7_fu_1127_p1 = t2_35_fu_1121_p2[24:0];

assign trunc_ln29_8_fu_923_p1 = t4_40_fu_917_p2[15:0];

assign trunc_ln29_9_fu_957_p1 = t2_36_fu_951_p2[19:0];

assign trunc_ln29_fu_1018_p1 = t4_36_fu_1013_p2[15:0];

assign trunc_ln65_fu_2074_p1 = i_3_fu_178[3:0];

assign trunc_ln8_1_fu_2159_p1 = x_q1[7:0];

assign trunc_ln8_2_fu_2217_p1 = x_q0[7:0];

assign trunc_ln8_3_fu_2275_p1 = x_q1[7:0];

assign trunc_ln8_fu_2101_p1 = x_q0[7:0];

assign zext_ln10_1_fu_2180_p1 = or_ln10_1_fu_2175_p2;

assign zext_ln10_2_fu_2238_p1 = or_ln10_2_fu_2233_p2;

assign zext_ln10_3_fu_2296_p1 = or_ln10_3_fu_2291_p2;

assign zext_ln10_fu_2122_p1 = or_ln10_fu_2117_p2;

assign zext_ln11_1_fu_2190_p1 = or_ln11_1_fu_2185_p2;

assign zext_ln11_2_fu_2248_p1 = or_ln11_2_fu_2243_p2;

assign zext_ln11_3_fu_2306_p1 = or_ln11_3_fu_2301_p2;

assign zext_ln11_fu_2132_p1 = or_ln11_fu_2127_p2;

assign zext_ln63_fu_2061_p1 = i_3_fu_178;

assign zext_ln65_1_fu_2142_p1 = or_ln63_fu_2137_p2;

assign zext_ln65_2_fu_2154_p1 = shl_ln65_1_fu_2147_p3;

assign zext_ln65_3_fu_2200_p1 = or_ln63_1_fu_2195_p2;

assign zext_ln65_4_fu_2212_p1 = shl_ln65_2_fu_2205_p3;

assign zext_ln65_5_fu_2258_p1 = or_ln63_2_fu_2253_p2;

assign zext_ln65_6_fu_2270_p1 = shl_ln65_3_fu_2263_p3;

assign zext_ln65_fu_2096_p1 = shl_ln_fu_2089_p3;

assign zext_ln9_1_fu_2170_p1 = or_ln9_1_fu_2164_p2;

assign zext_ln9_2_fu_2228_p1 = or_ln9_2_fu_2222_p2;

assign zext_ln9_3_fu_2286_p1 = or_ln9_3_fu_2280_p2;

assign zext_ln9_fu_2112_p1 = or_ln9_fu_2106_p2;

always @ (posedge ap_clk) begin
    shl_ln_reg_2971[1:0] <= 2'b00;
    or_ln63_reg_2977[0] <= 1'b1;
    shl_ln65_1_reg_2987[2:0] <= 3'b100;
    or_ln63_1_reg_2993[1] <= 1'b1;
    shl_ln65_2_reg_3003[1:0] <= 2'b00;
    shl_ln65_2_reg_3003[3] <= 1'b1;
    or_ln63_2_reg_3009[1:0] <= 2'b11;
    shl_ln65_3_reg_3019[3:0] <= 4'b1100;
end

endmodule //ChaCha20XOR_chacha20_block
