// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ChaCha20XOR_chacha20_init_state (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_address0,
        s_ce0,
        s_we0,
        s_d0,
        key_address0,
        key_ce0,
        key_q0,
        counter,
        nonce_address0,
        nonce_ce0,
        nonce_q0
);

parameter    ap_ST_fsm_state1 = 38'd1;
parameter    ap_ST_fsm_state2 = 38'd2;
parameter    ap_ST_fsm_state3 = 38'd4;
parameter    ap_ST_fsm_state4 = 38'd8;
parameter    ap_ST_fsm_state5 = 38'd16;
parameter    ap_ST_fsm_state6 = 38'd32;
parameter    ap_ST_fsm_state7 = 38'd64;
parameter    ap_ST_fsm_state8 = 38'd128;
parameter    ap_ST_fsm_state9 = 38'd256;
parameter    ap_ST_fsm_state10 = 38'd512;
parameter    ap_ST_fsm_state11 = 38'd1024;
parameter    ap_ST_fsm_state12 = 38'd2048;
parameter    ap_ST_fsm_state13 = 38'd4096;
parameter    ap_ST_fsm_state14 = 38'd8192;
parameter    ap_ST_fsm_state15 = 38'd16384;
parameter    ap_ST_fsm_state16 = 38'd32768;
parameter    ap_ST_fsm_state17 = 38'd65536;
parameter    ap_ST_fsm_state18 = 38'd131072;
parameter    ap_ST_fsm_state19 = 38'd262144;
parameter    ap_ST_fsm_state20 = 38'd524288;
parameter    ap_ST_fsm_state21 = 38'd1048576;
parameter    ap_ST_fsm_state22 = 38'd2097152;
parameter    ap_ST_fsm_state23 = 38'd4194304;
parameter    ap_ST_fsm_state24 = 38'd8388608;
parameter    ap_ST_fsm_state25 = 38'd16777216;
parameter    ap_ST_fsm_state26 = 38'd33554432;
parameter    ap_ST_fsm_state27 = 38'd67108864;
parameter    ap_ST_fsm_state28 = 38'd134217728;
parameter    ap_ST_fsm_state29 = 38'd268435456;
parameter    ap_ST_fsm_state30 = 38'd536870912;
parameter    ap_ST_fsm_state31 = 38'd1073741824;
parameter    ap_ST_fsm_state32 = 38'd2147483648;
parameter    ap_ST_fsm_state33 = 38'd4294967296;
parameter    ap_ST_fsm_state34 = 38'd8589934592;
parameter    ap_ST_fsm_state35 = 38'd17179869184;
parameter    ap_ST_fsm_state36 = 38'd34359738368;
parameter    ap_ST_fsm_state37 = 38'd68719476736;
parameter    ap_ST_fsm_state38 = 38'd137438953472;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] s_address0;
output   s_ce0;
output   s_we0;
output  [31:0] s_d0;
output  [4:0] key_address0;
output   key_ce0;
input  [7:0] key_q0;
input  [31:0] counter;
output  [3:0] nonce_address0;
output   nonce_ce0;
input  [7:0] nonce_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] s_address0;
reg s_ce0;
reg s_we0;
reg[31:0] s_d0;
reg[4:0] key_address0;
reg key_ce0;
reg[3:0] nonce_address0;
reg nonce_ce0;

(* fsm_encoding = "none" *) reg   [37:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state32;
wire    ap_CS_fsm_state33;
reg   [3:0] i_2_reg_1354;
wire    ap_CS_fsm_state34;
wire   [4:0] shl_ln_fu_1052_p3;
reg   [4:0] shl_ln_reg_1362;
wire   [0:0] icmp_ln125_fu_1036_p2;
wire   [7:0] kv_q1;
reg   [7:0] t_reg_1378;
wire    ap_CS_fsm_state35;
wire   [7:0] kv_q0;
reg   [7:0] t_4_reg_1383;
reg   [4:0] kv_address0;
reg    kv_ce0;
reg    kv_we0;
reg   [4:0] kv_address1;
reg    kv_ce1;
reg   [2:0] nv_address0;
reg    nv_ce0;
reg    nv_we0;
wire   [7:0] nv_q0;
reg    nv_ce1;
wire   [7:0] nv_q1;
reg   [2:0] nv_1_address0;
reg    nv_1_ce0;
reg    nv_1_we0;
wire   [7:0] nv_1_q0;
reg    nv_1_ce1;
wire   [7:0] nv_1_q1;
wire    grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_start;
wire    grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_done;
wire    grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_idle;
wire    grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_ready;
wire   [2:0] grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_address0;
wire    grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_ce0;
wire   [2:0] grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_address1;
wire    grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_ce1;
wire   [2:0] grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_1_address0;
wire    grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_1_ce0;
wire   [2:0] grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_1_address1;
wire    grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_1_ce1;
wire   [3:0] grp_chacha20_init_state_Pipeline_init_second_fu_1020_s_address0;
wire    grp_chacha20_init_state_Pipeline_init_second_fu_1020_s_ce0;
wire    grp_chacha20_init_state_Pipeline_init_second_fu_1020_s_we0;
wire   [31:0] grp_chacha20_init_state_Pipeline_init_second_fu_1020_s_d0;
reg    grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_start_reg;
wire    ap_CS_fsm_state37;
wire    ap_CS_fsm_state38;
wire   [63:0] zext_ln127_fu_1060_p1;
wire   [63:0] zext_ln128_fu_1071_p1;
wire   [63:0] zext_ln129_fu_1086_p1;
wire   [63:0] zext_ln130_fu_1096_p1;
wire   [63:0] zext_ln131_fu_1117_p1;
wire    ap_CS_fsm_state36;
reg   [3:0] i_fu_128;
wire   [3:0] add_ln125_fu_1042_p2;
wire   [31:0] value_fu_1101_p5;
wire   [2:0] trunc_ln127_fu_1048_p1;
wire   [4:0] or_ln128_fu_1065_p2;
wire   [4:0] or_ln129_fu_1081_p2;
wire   [4:0] or_ln130_fu_1091_p2;
wire   [3:0] add_ln131_fu_1112_p2;
reg   [37:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
reg    ap_ST_fsm_state38_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 38'd1;
#0 grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_start_reg = 1'b0;
end

ChaCha20XOR_chacha20_init_state_kv_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
kv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kv_address0),
    .ce0(kv_ce0),
    .we0(kv_we0),
    .d0(key_q0),
    .q0(kv_q0),
    .address1(kv_address1),
    .ce1(kv_ce1),
    .q1(kv_q1)
);

ChaCha20XOR_chacha20_init_state_nv_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
nv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(nv_address0),
    .ce0(nv_ce0),
    .we0(nv_we0),
    .d0(nonce_q0),
    .q0(nv_q0),
    .address1(grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_address1),
    .ce1(nv_ce1),
    .q1(nv_q1)
);

ChaCha20XOR_chacha20_init_state_nv_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
nv_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(nv_1_address0),
    .ce0(nv_1_ce0),
    .we0(nv_1_we0),
    .d0(nonce_q0),
    .q0(nv_1_q0),
    .address1(grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_1_address1),
    .ce1(nv_1_ce1),
    .q1(nv_1_q1)
);

ChaCha20XOR_chacha20_init_state_Pipeline_init_second grp_chacha20_init_state_Pipeline_init_second_fu_1020(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_start),
    .ap_done(grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_done),
    .ap_idle(grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_idle),
    .ap_ready(grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_ready),
    .nv_address0(grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_address0),
    .nv_ce0(grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_ce0),
    .nv_q0(nv_q0),
    .nv_address1(grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_address1),
    .nv_ce1(grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_ce1),
    .nv_q1(nv_q1),
    .nv_1_address0(grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_1_address0),
    .nv_1_ce0(grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_1_ce0),
    .nv_1_q0(nv_1_q0),
    .nv_1_address1(grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_1_address1),
    .nv_1_ce1(grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_1_ce1),
    .nv_1_q1(nv_1_q1),
    .s_address0(grp_chacha20_init_state_Pipeline_init_second_fu_1020_s_address0),
    .s_ce0(grp_chacha20_init_state_Pipeline_init_second_fu_1020_s_ce0),
    .s_we0(grp_chacha20_init_state_Pipeline_init_second_fu_1020_s_we0),
    .s_d0(grp_chacha20_init_state_Pipeline_init_second_fu_1020_s_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state37)) begin
            grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_start_reg <= 1'b1;
        end else if ((grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_ready == 1'b1)) begin
            grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_128 <= 4'd0;
    end else if (((icmp_ln125_fu_1036_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state34))) begin
        i_fu_128 <= add_ln125_fu_1042_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        i_2_reg_1354 <= i_fu_128;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln125_fu_1036_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state34))) begin
        shl_ln_reg_1362[4 : 2] <= shl_ln_fu_1052_p3[4 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        t_4_reg_1383 <= kv_q0;
        t_reg_1378 <= kv_q1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

always @ (*) begin
    if ((grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_done == 1'b0)) begin
        ap_ST_fsm_state38_blk = 1'b1;
    end else begin
        ap_ST_fsm_state38_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state38)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state38))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        key_address0 = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        key_address0 = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        key_address0 = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        key_address0 = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        key_address0 = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        key_address0 = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        key_address0 = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        key_address0 = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        key_address0 = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        key_address0 = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        key_address0 = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        key_address0 = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        key_address0 = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        key_address0 = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        key_address0 = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        key_address0 = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        key_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        key_address0 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        key_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        key_address0 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        key_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        key_address0 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        key_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        key_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        key_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        key_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        key_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        key_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        key_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        key_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        key_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        key_address0 = 64'd0;
    end else begin
        key_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        key_ce0 = 1'b1;
    end else begin
        key_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        kv_address0 = zext_ln129_fu_1086_p1;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        kv_address0 = zext_ln128_fu_1071_p1;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        kv_address0 = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        kv_address0 = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        kv_address0 = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        kv_address0 = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        kv_address0 = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        kv_address0 = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        kv_address0 = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        kv_address0 = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        kv_address0 = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        kv_address0 = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        kv_address0 = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        kv_address0 = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        kv_address0 = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        kv_address0 = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        kv_address0 = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        kv_address0 = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        kv_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        kv_address0 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        kv_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        kv_address0 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        kv_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        kv_address0 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        kv_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        kv_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        kv_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        kv_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        kv_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        kv_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        kv_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        kv_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        kv_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        kv_address0 = 64'd0;
    end else begin
        kv_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        kv_address1 = zext_ln130_fu_1096_p1;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        kv_address1 = zext_ln127_fu_1060_p1;
    end else begin
        kv_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        kv_ce0 = 1'b1;
    end else begin
        kv_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34))) begin
        kv_ce1 = 1'b1;
    end else begin
        kv_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        kv_we0 = 1'b1;
    end else begin
        kv_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        nonce_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        nonce_address0 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        nonce_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        nonce_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        nonce_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        nonce_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        nonce_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        nonce_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        nonce_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        nonce_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        nonce_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        nonce_address0 = 64'd0;
    end else begin
        nonce_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        nonce_ce0 = 1'b1;
    end else begin
        nonce_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        nv_1_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        nv_1_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        nv_1_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        nv_1_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        nv_1_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        nv_1_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        nv_1_address0 = grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_1_address0;
    end else begin
        nv_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5))) begin
        nv_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        nv_1_ce0 = grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_1_ce0;
    end else begin
        nv_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        nv_1_ce1 = grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_1_ce1;
    end else begin
        nv_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5))) begin
        nv_1_we0 = 1'b1;
    end else begin
        nv_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        nv_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        nv_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        nv_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        nv_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        nv_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        nv_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        nv_address0 = grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_address0;
    end else begin
        nv_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        nv_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        nv_ce0 = grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_ce0;
    end else begin
        nv_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        nv_ce1 = grp_chacha20_init_state_Pipeline_init_second_fu_1020_nv_ce1;
    end else begin
        nv_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        nv_we0 = 1'b1;
    end else begin
        nv_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        s_address0 = zext_ln131_fu_1117_p1;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        s_address0 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        s_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        s_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        s_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        s_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        s_address0 = grp_chacha20_init_state_Pipeline_init_second_fu_1020_s_address0;
    end else begin
        s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        s_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        s_ce0 = grp_chacha20_init_state_Pipeline_init_second_fu_1020_s_ce0;
    end else begin
        s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        s_d0 = value_fu_1101_p5;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        s_d0 = counter;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        s_d0 = 32'd1797285236;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        s_d0 = 32'd857760878;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        s_d0 = 32'd2036477234;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        s_d0 = 32'd1634760805;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        s_d0 = grp_chacha20_init_state_Pipeline_init_second_fu_1020_s_d0;
    end else begin
        s_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln125_fu_1036_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state34)))) begin
        s_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        s_we0 = grp_chacha20_init_state_Pipeline_init_second_fu_1020_s_we0;
    end else begin
        s_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            if (((icmp_ln125_fu_1036_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state34))) begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            if (((grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state38))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln125_fu_1042_p2 = (i_fu_128 + 4'd1);

assign add_ln131_fu_1112_p2 = (i_2_reg_1354 + 4'd4);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_start = grp_chacha20_init_state_Pipeline_init_second_fu_1020_ap_start_reg;

assign icmp_ln125_fu_1036_p2 = ((i_fu_128 == 4'd8) ? 1'b1 : 1'b0);

assign or_ln128_fu_1065_p2 = (shl_ln_fu_1052_p3 | 5'd1);

assign or_ln129_fu_1081_p2 = (shl_ln_reg_1362 | 5'd2);

assign or_ln130_fu_1091_p2 = (shl_ln_reg_1362 | 5'd3);

assign shl_ln_fu_1052_p3 = {{trunc_ln127_fu_1048_p1}, {2'd0}};

assign trunc_ln127_fu_1048_p1 = i_fu_128[2:0];

assign value_fu_1101_p5 = {{{{kv_q1}, {kv_q0}}, {t_4_reg_1383}}, {t_reg_1378}};

assign zext_ln127_fu_1060_p1 = shl_ln_fu_1052_p3;

assign zext_ln128_fu_1071_p1 = or_ln128_fu_1065_p2;

assign zext_ln129_fu_1086_p1 = or_ln129_fu_1081_p2;

assign zext_ln130_fu_1096_p1 = or_ln130_fu_1091_p2;

assign zext_ln131_fu_1117_p1 = add_ln131_fu_1112_p2;

always @ (posedge ap_clk) begin
    shl_ln_reg_1362[1:0] <= 2'b00;
end

endmodule //ChaCha20XOR_chacha20_init_state
